name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy-dev:
    needs: lint
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit
